import crypto from 'crypto';
import fs from 'fs/promises';
import path from 'path';

const TEST_DATA_DIR = path.join(process.cwd(), 'data-test');
const KEY_LENGTH = 64;

const MOCK_CAPSULE = {
  metadata: {
    capsule_id: 'capsule.test.setup.v1',
    version: '1.0.0',
    status: 'sovereign',
    type: 'concept',
    subtype: 'atomic',
    author: 'Test Suite',
    created_at: new Date().toISOString(),
    semantic_hash: 'test-setup-initial-capsule-mock-data-gold',
  },
  core_payload: {
    content_type: 'markdown',
    content: '# Initial Setup Capsule\nMock capsule generated by globalSetup for E2E tests.',
  },
  neuro_concentrate: {
    summary: 'Mock capsule generated by globalSetup for E2E tests.',
    keywords: ['test', 'setup'],
    confidence_vector: [1, 1, 1, 1, 1, 0],
    semantic_hash: 'test-setup-initial-capsule-mock-data-gold',
  },
  recursive_layer: { links: [], actions: [], epistemic_ledger: [] },
  integrity_sha3_512: 'abc123mockhash',
};

const scryptBuffer = async (password: string, salt: Buffer) => {
  return await new Promise<Buffer>((resolve, reject) => {
    crypto.scrypt(
      password,
      salt,
      KEY_LENGTH,
      { N: 16384, r: 8, p: 1 },
      (err, derivedKey) => {
        if (err) {
          reject(err);
          return;
        }
        resolve(derivedKey as Buffer);
      },
    );
  });
};

const buildPasswordHash = async (password: string) => {
  const salt = crypto.randomBytes(16);
  const hash = await scryptBuffer(password, salt);
  return `scrypt$16384$8$1$${salt.toString('hex')}$${hash.toString('hex')}`;
};

export default async function globalSetup() {
  console.log('--- Playwright Global Setup: initializing data-test ---');

  await fs.rm(TEST_DATA_DIR, { recursive: true, force: true });
  await fs.mkdir(path.join(TEST_DATA_DIR, 'capsules'), { recursive: true });
  await fs.mkdir(path.join(TEST_DATA_DIR, 'versions'), { recursive: true });

  const passwordHash = await buildPasswordHash('testpass123');
  await fs.writeFile(path.join(TEST_DATA_DIR, 'password.txt'), passwordHash, 'utf-8');

  await fs.writeFile(
    path.join(TEST_DATA_DIR, 'capsules', 'capsule.test.setup.v1.json'),
    JSON.stringify(MOCK_CAPSULE, null, 2),
    'utf-8',
  );

  await fs.writeFile(path.join(TEST_DATA_DIR, 'activity.log'), '', 'utf-8');

  console.log('--- Playwright Global Setup Complete ---');
}
